[package]
name = "rust-course"
version = "0.1.0"
authors = ["Jirawat Harnsiriwatanakit <jirawat.h@inception.asia>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
